### ISSUE TITLE
What's the license for these servers?

### ISSUE THREAD

**Issue by abailly** [sopra-steria-norge/extreme_startup_servers#12]
Hello,
I would like to know what's the license for those sample servers? 

Thanks
Arnaud

**Comment by olillevik** [comment]
You are the first to ask us this question. The code was forked from rchately found here: https://github.com/rchatley/extreme_startup. As a consequence of this we will not licence our code until such a time as rchatley has chosen a license for his work. We will follow his lead. In other words, you have to ask him to choose an open source license before I dare do the same for our repository. Thank you for your interest in our work. Our intent is for it to be used freely.

**Comment by abailly** [comment]
My question was specifically targeted at the license regarding the skeletal
servers, not the extreme startup game server, which are two different
things IMHO. Thanks for your answer anyway, I will ask Robert what's are
its plan regarding XS license and maybe get back to you.

Thanks again,

## 

Arnaud Bailly
FoldLabs Associate: http://foldlabs.com

**Comment by olillevik** [comment]
Your point is valid. I have added a permissive license. BSD 2.

**Comment by rchatley** [comment]
Just to say, prompted by this, I added a creative commons licence to the main extreme startup code.
https://github.com/rchatley/extreme_startup/blob/master/LICENSE.md

cheers,
Robert
